const dates = {
    dates: [
        {
            available_dates: [
                {
                    available_date_id: 1,
                    id: 1,
                    is_available: false,
                    session_id: null,
                    time: "04:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 2,
                    is_available: false,
                    session_id: null,
                    time: "04:30 pm",
                },
                {
                    available_date_id: 1,
                    id: 3,
                    is_available: false,
                    session_id: null,
                    time: "05:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 4,
                    is_available: false,
                    session_id: null,
                    time: "05:30 pm",
                },
                {
                    available_date_id: 1,
                    id: 5,
                    is_available: false,
                    session_id: null,
                    time: "06:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 6,
                    is_available: false,
                    session_id: null,
                    time: "06:30 pm",
                },
                {
                    available_date_id: 1,
                    id: 7,
                    is_available: false,
                    session_id: null,
                    time: "07:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 8,
                    is_available: false,
                    session_id: null,
                    time: "07:30 pm",
                },
                {
                    available_date_id: 1,
                    id: 9,
                    is_available: false,
                    session_id: null,
                    time: "08:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 10,
                    is_available: false,
                    session_id: null,
                    time: "08:30 pm",
                },
                {
                    available_date_id: 1,
                    id: 11,
                    is_available: false,
                    session_id: null,
                    time: "09:00 pm",
                },
                {
                    available_date_id: 1,
                    id: 12,
                    is_available: false,
                    session_id: null,
                    time: "09:30 pm",
                },
            ],
            day: "Sunday",
            doctor_id: 5,
            end_time: "10:00 pm",
            id: 1,
            start_time: "04:00 pm",
        },
        {
            available_dates: [
                {
                    available_date_id: 2,
                    id: 13,
                    is_available: false,
                    session_id: null,
                    time: "05:00 pm",
                },
                {
                    available_date_id: 2,
                    id: 14,
                    is_available: false,
                    session_id: null,
                    time: "05:30 pm",
                },
                {
                    available_date_id: 2,
                    id: 15,
                    is_available: false,
                    session_id: null,
                    time: "06:00 pm",
                },
                {
                    available_date_id: 2,
                    id: 16,
                    is_available: false,
                    session_id: null,
                    time: "06:30 pm",
                },
                {
                    available_date_id: 2,
                    id: 17,
                    is_available: false,
                    session_id: null,
                    time: "07:00 pm",
                },
                {
                    available_date_id: 2,
                    id: 18,
                    is_available: false,
                    session_id: null,
                    time: "07:30 pm",
                },
                {
                    available_date_id: 2,
                    id: 19,
                    is_available: false,
                    session_id: null,
                    time: "08:00 pm",
                },
                {
                    available_date_id: 2,
                    id: 20,
                    is_available: false,
                    session_id: null,
                    time: "08:30 pm",
                },
                {
                    available_date_id: 2,
                    id: 21,
                    is_available: false,
                    session_id: null,
                    time: "09:00 pm",
                },
                {
                    available_date_id: 2,
                    id: 22,
                    is_available: false,
                    session_id: null,
                    time: "09:30 pm",
                },
            ],
            day: "Tuesday",
            doctor_id: 5,
            end_time: "10:00 pm",
            id: 7,
            start_time: "05:00 pm",
        },
    ],
    success: true,
};
export default dates;